AV/catalogo_de_filmes/cat_filmes/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import index, cadastro, deletar
from rest_framework import routers
from .api.viewsets import FilmeViewSet

router = routers.DefaultRouter()
router.register('api_filmes', FilmeViewSet)

urlpatterns = [
    path('', index, name='index'),
    path('cadastro/', cadastro, name='cadastro'),
    path('deletar/<int:id>', deletar, name='deletar'),
    path('api_filme', include(router.urls))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AV/catalogo_de_filmes/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cat_filmes.urls')),
]

AV/catalogo_de_filmes/cat_filmes/models.py
from django.db import models

class Filme(models.Model):

    GENERO_CHOICES = (
        ('AC', 'Ação'),
        ('AV', 'Aventura'),
        ('RO', 'Romance'),
        ('TE', 'Terror'),
        ('DR', 'Drama'),
        ('SU', 'Suspense'),
        ('EC', 'Ficção Cientifica'),
        ('DO', 'Documentario'),
        ('AN', 'Animação'),
        ('NS', 'Não selecionado')
        )
    
    titulo = models.CharField(max_length=100)
    diretor = models.CharField(max_length=60)
    sinopse = models.TextField()
    ano_lancamento = models.DateField()
    duracao = models.IntegerField(default=0)
    genero = models.CharField(max_length=2, choices=GENERO_CHOICES, default='NS')
    data_cad = models.DateTimeField(auto_now_add=True)
    imagem = models.ImageField(upload_to='capas', null=True, blank=True)

    def __str__(self):
        return self.titulo

AV/catalogo_de_filmes/cat_filmes/forms.py
from django import forms
from .models import Filme

class FilmeForm(forms.ModelForm):
    class Meta:
        model = Filme
        fields = '__all__'

AV/catalogo_de_filmes/cat_filmes/views.py
from django.shortcuts import render, redirect
from .models import Filme
from django.contrib import messages
from .forms import FilmeForm

def index (request):
    filmes = Filme.objects.all()
    context = {
        'filmes': filmes,
    }
    return render(request, 'cat_filmes/index.html', context)

def cadastro(request):
    if request.method == 'POST':
        form = FilmeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request,'Filme Cadastrado com sucesso')
            form = FilmeForm()
        else: 
            messages.error(request, 'Erro ao salvar o filme')
    else:
        form = FilmeForm()
    return render(request, 'cat_filmes/cadastro.html',{'form': form})

def deletar(request, id):
    delete_me = Filme.objects.get(id=id)
    if request.method == 'POST':
        delete_me.delete()
        return redirect('/')
    return render(request, 'cat_filmes/deletar.html')
    

AV/catalogo_de_filmes/cat_filmes/templates/cat_filmes/cadastro.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>
    {% bootstrap_css %}
</head>
<body>
    <div class='container'>
        <h2>Cadastro de filmes</h2>
        <a href="{% url 'index'%}">Index</a>
        <div class="container">
            {% bootstrap_messages %}
            <form action="{% url 'cadastro' %}" method="post" class="form" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                {% endbuttons %}
            </form>

        </div>
    </div>
    {% bootstrap_javascript %}
</body>
</html>

AV/catalogo_de_filmes/cat_filmes/templates/cat_filmes/deletar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Deletar filme</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        Você tem certeza que deseja deletar?
        <input type="submit">
    </form>
</body>
</html>

AV/catalogo_de_filmes/cat_filmes/templates/cat_filmes/index.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Catalogo de filmes</title>
    {% bootstrap_css %}
</head>
<body>
    <div class="container">
        <a href="{% url 'cadastro' %}">Cadastrar Filme</a>
        <h2>Filmes</h2>
        <div class="row">
            {% for filme in filmes %}
            <div class="col">
                <img class="img-thumbnail" src="media/{{filme.imagem}}" alt="Capa do filme">
                <h2>Titulo: {{filme.titulo}}</h2>
                <h3>Diretor: {{filme.diretor}}</h3>
                <p>Sinopse: {{filme.sinopse}}</p>
                <span>Ano de lançamento: {{filme.ano_lancamento}}</span><br>
                <span>Duração: {{filme.duracao}}min</span><br>
                <span>Genero: {{filme.get_genero_display}}</span><br>
                <a class="btn btn-danger" href="{% url 'deletar' filme.id %}">Deletar Filme</a>
            </div>
            {% endfor %}
            
        </div>
       
    </div>
    {% bootstrap_javascript %}
</body>
</html>